// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9HSOuEhpRlhEyRnyZoNXBA7M-ciAZ1I',
    appId: '1:756642158369:web:d3acc50974080a2b095060',
    messagingSenderId: '756642158369',
    projectId: 'mentu-20',
    authDomain: 'mentu-20.firebaseapp.com',
    storageBucket: 'mentu-20.firebasestorage.app',
    measurementId: 'G-3SHBSPX0W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDQ0esdUa93e0DNEBC0hYWOXiDvtfXP4',
    appId: '1:756642158369:android:e2c4568435b244a9095060',
    messagingSenderId: '756642158369',
    projectId: 'mentu-20',
    storageBucket: 'mentu-20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphq2bh6t3UVbPAija7G4DvMm5MgBd2Pc',
    appId: '1:756642158369:ios:859fddb939dbdb35095060',
    messagingSenderId: '756642158369',
    projectId: 'mentu-20',
    storageBucket: 'mentu-20.firebasestorage.app',
    iosBundleId: 'com.example.mentuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDphq2bh6t3UVbPAija7G4DvMm5MgBd2Pc',
    appId: '1:756642158369:ios:859fddb939dbdb35095060',
    messagingSenderId: '756642158369',
    projectId: 'mentu-20',
    storageBucket: 'mentu-20.firebasestorage.app',
    iosBundleId: 'com.example.mentuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ9HSOuEhpRlhEyRnyZoNXBA7M-ciAZ1I',
    appId: '1:756642158369:web:481ba43c7acee36d095060',
    messagingSenderId: '756642158369',
    projectId: 'mentu-20',
    authDomain: 'mentu-20.firebaseapp.com',
    storageBucket: 'mentu-20.firebasestorage.app',
    measurementId: 'G-HYG2J4RRMJ',
  );
}
